---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - env | sort
      - make install

  # TODO: Run tests

  # TODO: Need to install linters e.g. cfn-lint, etc
  # pre_build:
  #   commands:
  #     - make lint

  build:
    commands:
      - make dist
      - mv dist actions
      # TODO: Remove, debugging
      - ls -al

artifacts:
  base-directory: actions
  files:
    - actions/**/*
