---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - env | sort
      # TODO: Need to install linters e.g. cfn-lint, etc
      - make install

  pre_build:
    commands:
      # - make lint
      # - make test
      - npm run test:unit

  build:
    commands:
      - make dist

  # Rename directory to support Distribution path behavior
  post_build:
    commands:
      - mv dist actions

artifacts:
  files:
    - actions/**/*
